# Generated by Django 2.2.1 on 2019-05-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='hit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
