# Generated by Django 2.2.1 on 2019-05-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_notice_file'),
        ('notice', '0002_notice_hit'),
    ]

    operations = [
    ]
