# Generated by Django 2.2.1 on 2019-05-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
