# Generated by Django 2.2.1 on 2019-05-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0004_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(null=True, upload_to='document/'),
        ),
    ]
