# Generated by Django 2.2.1 on 2019-05-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20190524_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(null=True, upload_to='notice/'),
        ),
    ]
