# Generated by Django 2.2.1 on 2019-05-31 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0006_auto_20190531_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
